# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ZKFCProtocol.proto',
  package='hadoop.common',
  serialized_pb='\n\x12ZKFCProtocol.proto\x12\rhadoop.common\".\n\x16\x43\x65\x64\x65\x41\x63tiveRequestProto\x12\x14\n\x0cmillisToCede\x18\x01 \x02(\r\"\x19\n\x17\x43\x65\x64\x65\x41\x63tiveResponseProto\"\x1e\n\x1cGracefulFailoverRequestProto\"\x1f\n\x1dGracefulFailoverResponseProto2\xe1\x01\n\x13ZKFCProtocolService\x12[\n\ncedeActive\x12%.hadoop.common.CedeActiveRequestProto\x1a&.hadoop.common.CedeActiveResponseProto\x12m\n\x10gracefulFailover\x12+.hadoop.common.GracefulFailoverRequestProto\x1a,.hadoop.common.GracefulFailoverResponseProtoB9\n\x1aorg.apache.hadoop.ha.protoB\x12ZKFCProtocolProtos\x88\x01\x01\x90\x01\x01\xa0\x01\x01')




_CEDEACTIVEREQUESTPROTO = descriptor.Descriptor(
  name='CedeActiveRequestProto',
  full_name='hadoop.common.CedeActiveRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='millisToCede', full_name='hadoop.common.CedeActiveRequestProto.millisToCede', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=83,
)


_CEDEACTIVERESPONSEPROTO = descriptor.Descriptor(
  name='CedeActiveResponseProto',
  full_name='hadoop.common.CedeActiveResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=85,
  serialized_end=110,
)


_GRACEFULFAILOVERREQUESTPROTO = descriptor.Descriptor(
  name='GracefulFailoverRequestProto',
  full_name='hadoop.common.GracefulFailoverRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=112,
  serialized_end=142,
)


_GRACEFULFAILOVERRESPONSEPROTO = descriptor.Descriptor(
  name='GracefulFailoverResponseProto',
  full_name='hadoop.common.GracefulFailoverResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['CedeActiveRequestProto'] = _CEDEACTIVEREQUESTPROTO
DESCRIPTOR.message_types_by_name['CedeActiveResponseProto'] = _CEDEACTIVERESPONSEPROTO
DESCRIPTOR.message_types_by_name['GracefulFailoverRequestProto'] = _GRACEFULFAILOVERREQUESTPROTO
DESCRIPTOR.message_types_by_name['GracefulFailoverResponseProto'] = _GRACEFULFAILOVERRESPONSEPROTO

class CedeActiveRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CEDEACTIVEREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.CedeActiveRequestProto)

class CedeActiveResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CEDEACTIVERESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.CedeActiveResponseProto)

class GracefulFailoverRequestProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GRACEFULFAILOVERREQUESTPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.GracefulFailoverRequestProto)

class GracefulFailoverResponseProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GRACEFULFAILOVERRESPONSEPROTO
  
  # @@protoc_insertion_point(class_scope:hadoop.common.GracefulFailoverResponseProto)


_ZKFCPROTOCOLSERVICE = descriptor.ServiceDescriptor(
  name='ZKFCProtocolService',
  full_name='hadoop.common.ZKFCProtocolService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=178,
  serialized_end=403,
  methods=[
  descriptor.MethodDescriptor(
    name='cedeActive',
    full_name='hadoop.common.ZKFCProtocolService.cedeActive',
    index=0,
    containing_service=None,
    input_type=_CEDEACTIVEREQUESTPROTO,
    output_type=_CEDEACTIVERESPONSEPROTO,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='gracefulFailover',
    full_name='hadoop.common.ZKFCProtocolService.gracefulFailover',
    index=1,
    containing_service=None,
    input_type=_GRACEFULFAILOVERREQUESTPROTO,
    output_type=_GRACEFULFAILOVERRESPONSEPROTO,
    options=None,
  ),
])

class ZKFCProtocolService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _ZKFCPROTOCOLSERVICE
class ZKFCProtocolService_Stub(ZKFCProtocolService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _ZKFCPROTOCOLSERVICE

# @@protoc_insertion_point(module_scope)
