# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/resourcemanager_administration_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server import yarn_server_resourcemanager_service_protos_pb2 as server_dot_yarn__server__resourcemanager__service__protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/resourcemanager_administration_protocol.proto',
  package='hadoop.yarn',
  syntax='proto2',
  serialized_pb=_b('\n4server/resourcemanager_administration_protocol.proto\x12\x0bhadoop.yarn\x1a\x37server/yarn_server_resourcemanager_service_protos.proto2\xd8\n\n,ResourceManagerAdministrationProtocolService\x12`\n\rrefreshQueues\x12&.hadoop.yarn.RefreshQueuesRequestProto\x1a\'.hadoop.yarn.RefreshQueuesResponseProto\x12]\n\x0crefreshNodes\x12%.hadoop.yarn.RefreshNodesRequestProto\x1a&.hadoop.yarn.RefreshNodesResponseProto\x12\xa2\x01\n#refreshSuperUserGroupsConfiguration\x12<.hadoop.yarn.RefreshSuperUserGroupsConfigurationRequestProto\x1a=.hadoop.yarn.RefreshSuperUserGroupsConfigurationResponseProto\x12\x8a\x01\n\x1brefreshUserToGroupsMappings\x12\x34.hadoop.yarn.RefreshUserToGroupsMappingsRequestProto\x1a\x35.hadoop.yarn.RefreshUserToGroupsMappingsResponseProto\x12i\n\x10refreshAdminAcls\x12).hadoop.yarn.RefreshAdminAclsRequestProto\x1a*.hadoop.yarn.RefreshAdminAclsResponseProto\x12o\n\x12refreshServiceAcls\x12+.hadoop.yarn.RefreshServiceAclsRequestProto\x1a,.hadoop.yarn.RefreshServiceAclsResponseProto\x12i\n\x10getGroupsForUser\x12).hadoop.yarn.GetGroupsForUserRequestProto\x1a*.hadoop.yarn.GetGroupsForUserResponseProto\x12o\n\x12updateNodeResource\x12+.hadoop.yarn.UpdateNodeResourceRequestProto\x1a,.hadoop.yarn.UpdateNodeResourceResponseProto\x12{\n\x16\x61\x64\x64ToClusterNodeLabels\x12/.hadoop.yarn.AddToClusterNodeLabelsRequestProto\x1a\x30.hadoop.yarn.AddToClusterNodeLabelsResponseProto\x12\x8a\x01\n\x1bremoveFromClusterNodeLabels\x12\x34.hadoop.yarn.RemoveFromClusterNodeLabelsRequestProto\x1a\x35.hadoop.yarn.RemoveFromClusterNodeLabelsResponseProto\x12s\n\x14replaceLabelsOnNodes\x12,.hadoop.yarn.ReplaceLabelsOnNodeRequestProto\x1a-.hadoop.yarn.ReplaceLabelsOnNodeResponseProtoBK\n\x1corg.apache.hadoop.yarn.protoB%ResourceManagerAdministrationProtocol\x88\x01\x01\xa0\x01\x01')
  ,
  dependencies=[server_dot_yarn__server__resourcemanager__service__protos__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034org.apache.hadoop.yarn.protoB%ResourceManagerAdministrationProtocol\210\001\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
