# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/yarn_server_resourcemanager_service_protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yarn_protos_pb2 as yarn__protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/yarn_server_resourcemanager_service_protos.proto',
  package='hadoop.yarn',
  syntax='proto2',
  serialized_pb=_b('\n7server/yarn_server_resourcemanager_service_protos.proto\x12\x0bhadoop.yarn\x1a\x11yarn_protos.proto\"\x1b\n\x19RefreshQueuesRequestProto\"\x1c\n\x1aRefreshQueuesResponseProto\"\x1a\n\x18RefreshNodesRequestProto\"\x1b\n\x19RefreshNodesResponseProto\"1\n/RefreshSuperUserGroupsConfigurationRequestProto\"2\n0RefreshSuperUserGroupsConfigurationResponseProto\")\n\'RefreshUserToGroupsMappingsRequestProto\"*\n(RefreshUserToGroupsMappingsResponseProto\"\x1e\n\x1cRefreshAdminAclsRequestProto\"\x1f\n\x1dRefreshAdminAclsResponseProto\" \n\x1eRefreshServiceAclsRequestProto\"!\n\x1fRefreshServiceAclsResponseProto\",\n\x1cGetGroupsForUserRequestProto\x12\x0c\n\x04user\x18\x01 \x02(\t\"/\n\x1dGetGroupsForUserResponseProto\x12\x0e\n\x06groups\x18\x01 \x03(\t\"^\n\x1eUpdateNodeResourceRequestProto\x12<\n\x11node_resource_map\x18\x01 \x03(\x0b\x32!.hadoop.yarn.NodeResourceMapProto\"!\n\x1fUpdateNodeResourceResponseProto\"8\n\"AddToClusterNodeLabelsRequestProto\x12\x12\n\nnodeLabels\x18\x01 \x03(\t\"%\n#AddToClusterNodeLabelsResponseProto\"=\n\'RemoveFromClusterNodeLabelsRequestProto\x12\x12\n\nnodeLabels\x18\x01 \x03(\t\"*\n(RemoveFromClusterNodeLabelsResponseProto\"Y\n\x1fReplaceLabelsOnNodeRequestProto\x12\x36\n\x0cnodeToLabels\x18\x01 \x03(\x0b\x32 .hadoop.yarn.NodeIdToLabelsProto\"\"\n ReplaceLabelsOnNodeResponseProto\"4\n\x11\x41\x63tiveRMInfoProto\x12\x11\n\tclusterId\x18\x01 \x01(\t\x12\x0c\n\x04rmId\x18\x02 \x01(\tBL\n\x1corg.apache.hadoop.yarn.protoB&YarnServerResourceManagerServiceProtos\x88\x01\x01\xa0\x01\x01')
  ,
  dependencies=[yarn__protos__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REFRESHQUEUESREQUESTPROTO = _descriptor.Descriptor(
  name='RefreshQueuesRequestProto',
  full_name='hadoop.yarn.RefreshQueuesRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=118,
)


_REFRESHQUEUESRESPONSEPROTO = _descriptor.Descriptor(
  name='RefreshQueuesResponseProto',
  full_name='hadoop.yarn.RefreshQueuesResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=148,
)


_REFRESHNODESREQUESTPROTO = _descriptor.Descriptor(
  name='RefreshNodesRequestProto',
  full_name='hadoop.yarn.RefreshNodesRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=176,
)


_REFRESHNODESRESPONSEPROTO = _descriptor.Descriptor(
  name='RefreshNodesResponseProto',
  full_name='hadoop.yarn.RefreshNodesResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=205,
)


_REFRESHSUPERUSERGROUPSCONFIGURATIONREQUESTPROTO = _descriptor.Descriptor(
  name='RefreshSuperUserGroupsConfigurationRequestProto',
  full_name='hadoop.yarn.RefreshSuperUserGroupsConfigurationRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=256,
)


_REFRESHSUPERUSERGROUPSCONFIGURATIONRESPONSEPROTO = _descriptor.Descriptor(
  name='RefreshSuperUserGroupsConfigurationResponseProto',
  full_name='hadoop.yarn.RefreshSuperUserGroupsConfigurationResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=308,
)


_REFRESHUSERTOGROUPSMAPPINGSREQUESTPROTO = _descriptor.Descriptor(
  name='RefreshUserToGroupsMappingsRequestProto',
  full_name='hadoop.yarn.RefreshUserToGroupsMappingsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=351,
)


_REFRESHUSERTOGROUPSMAPPINGSRESPONSEPROTO = _descriptor.Descriptor(
  name='RefreshUserToGroupsMappingsResponseProto',
  full_name='hadoop.yarn.RefreshUserToGroupsMappingsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=395,
)


_REFRESHADMINACLSREQUESTPROTO = _descriptor.Descriptor(
  name='RefreshAdminAclsRequestProto',
  full_name='hadoop.yarn.RefreshAdminAclsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=427,
)


_REFRESHADMINACLSRESPONSEPROTO = _descriptor.Descriptor(
  name='RefreshAdminAclsResponseProto',
  full_name='hadoop.yarn.RefreshAdminAclsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=460,
)


_REFRESHSERVICEACLSREQUESTPROTO = _descriptor.Descriptor(
  name='RefreshServiceAclsRequestProto',
  full_name='hadoop.yarn.RefreshServiceAclsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=494,
)


_REFRESHSERVICEACLSRESPONSEPROTO = _descriptor.Descriptor(
  name='RefreshServiceAclsResponseProto',
  full_name='hadoop.yarn.RefreshServiceAclsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=529,
)


_GETGROUPSFORUSERREQUESTPROTO = _descriptor.Descriptor(
  name='GetGroupsForUserRequestProto',
  full_name='hadoop.yarn.GetGroupsForUserRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='hadoop.yarn.GetGroupsForUserRequestProto.user', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=575,
)


_GETGROUPSFORUSERRESPONSEPROTO = _descriptor.Descriptor(
  name='GetGroupsForUserResponseProto',
  full_name='hadoop.yarn.GetGroupsForUserResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='hadoop.yarn.GetGroupsForUserResponseProto.groups', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=624,
)


_UPDATENODERESOURCEREQUESTPROTO = _descriptor.Descriptor(
  name='UpdateNodeResourceRequestProto',
  full_name='hadoop.yarn.UpdateNodeResourceRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_resource_map', full_name='hadoop.yarn.UpdateNodeResourceRequestProto.node_resource_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=626,
  serialized_end=720,
)


_UPDATENODERESOURCERESPONSEPROTO = _descriptor.Descriptor(
  name='UpdateNodeResourceResponseProto',
  full_name='hadoop.yarn.UpdateNodeResourceResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=722,
  serialized_end=755,
)


_ADDTOCLUSTERNODELABELSREQUESTPROTO = _descriptor.Descriptor(
  name='AddToClusterNodeLabelsRequestProto',
  full_name='hadoop.yarn.AddToClusterNodeLabelsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeLabels', full_name='hadoop.yarn.AddToClusterNodeLabelsRequestProto.nodeLabels', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=757,
  serialized_end=813,
)


_ADDTOCLUSTERNODELABELSRESPONSEPROTO = _descriptor.Descriptor(
  name='AddToClusterNodeLabelsResponseProto',
  full_name='hadoop.yarn.AddToClusterNodeLabelsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=815,
  serialized_end=852,
)


_REMOVEFROMCLUSTERNODELABELSREQUESTPROTO = _descriptor.Descriptor(
  name='RemoveFromClusterNodeLabelsRequestProto',
  full_name='hadoop.yarn.RemoveFromClusterNodeLabelsRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeLabels', full_name='hadoop.yarn.RemoveFromClusterNodeLabelsRequestProto.nodeLabels', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=854,
  serialized_end=915,
)


_REMOVEFROMCLUSTERNODELABELSRESPONSEPROTO = _descriptor.Descriptor(
  name='RemoveFromClusterNodeLabelsResponseProto',
  full_name='hadoop.yarn.RemoveFromClusterNodeLabelsResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=917,
  serialized_end=959,
)


_REPLACELABELSONNODEREQUESTPROTO = _descriptor.Descriptor(
  name='ReplaceLabelsOnNodeRequestProto',
  full_name='hadoop.yarn.ReplaceLabelsOnNodeRequestProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeToLabels', full_name='hadoop.yarn.ReplaceLabelsOnNodeRequestProto.nodeToLabels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=961,
  serialized_end=1050,
)


_REPLACELABELSONNODERESPONSEPROTO = _descriptor.Descriptor(
  name='ReplaceLabelsOnNodeResponseProto',
  full_name='hadoop.yarn.ReplaceLabelsOnNodeResponseProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1052,
  serialized_end=1086,
)


_ACTIVERMINFOPROTO = _descriptor.Descriptor(
  name='ActiveRMInfoProto',
  full_name='hadoop.yarn.ActiveRMInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterId', full_name='hadoop.yarn.ActiveRMInfoProto.clusterId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rmId', full_name='hadoop.yarn.ActiveRMInfoProto.rmId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1088,
  serialized_end=1140,
)

_UPDATENODERESOURCEREQUESTPROTO.fields_by_name['node_resource_map'].message_type = yarn__protos__pb2._NODERESOURCEMAPPROTO
_REPLACELABELSONNODEREQUESTPROTO.fields_by_name['nodeToLabels'].message_type = yarn__protos__pb2._NODEIDTOLABELSPROTO
DESCRIPTOR.message_types_by_name['RefreshQueuesRequestProto'] = _REFRESHQUEUESREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshQueuesResponseProto'] = _REFRESHQUEUESRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshNodesRequestProto'] = _REFRESHNODESREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshNodesResponseProto'] = _REFRESHNODESRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshSuperUserGroupsConfigurationRequestProto'] = _REFRESHSUPERUSERGROUPSCONFIGURATIONREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshSuperUserGroupsConfigurationResponseProto'] = _REFRESHSUPERUSERGROUPSCONFIGURATIONRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshUserToGroupsMappingsRequestProto'] = _REFRESHUSERTOGROUPSMAPPINGSREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshUserToGroupsMappingsResponseProto'] = _REFRESHUSERTOGROUPSMAPPINGSRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshAdminAclsRequestProto'] = _REFRESHADMINACLSREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshAdminAclsResponseProto'] = _REFRESHADMINACLSRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RefreshServiceAclsRequestProto'] = _REFRESHSERVICEACLSREQUESTPROTO
DESCRIPTOR.message_types_by_name['RefreshServiceAclsResponseProto'] = _REFRESHSERVICEACLSRESPONSEPROTO
DESCRIPTOR.message_types_by_name['GetGroupsForUserRequestProto'] = _GETGROUPSFORUSERREQUESTPROTO
DESCRIPTOR.message_types_by_name['GetGroupsForUserResponseProto'] = _GETGROUPSFORUSERRESPONSEPROTO
DESCRIPTOR.message_types_by_name['UpdateNodeResourceRequestProto'] = _UPDATENODERESOURCEREQUESTPROTO
DESCRIPTOR.message_types_by_name['UpdateNodeResourceResponseProto'] = _UPDATENODERESOURCERESPONSEPROTO
DESCRIPTOR.message_types_by_name['AddToClusterNodeLabelsRequestProto'] = _ADDTOCLUSTERNODELABELSREQUESTPROTO
DESCRIPTOR.message_types_by_name['AddToClusterNodeLabelsResponseProto'] = _ADDTOCLUSTERNODELABELSRESPONSEPROTO
DESCRIPTOR.message_types_by_name['RemoveFromClusterNodeLabelsRequestProto'] = _REMOVEFROMCLUSTERNODELABELSREQUESTPROTO
DESCRIPTOR.message_types_by_name['RemoveFromClusterNodeLabelsResponseProto'] = _REMOVEFROMCLUSTERNODELABELSRESPONSEPROTO
DESCRIPTOR.message_types_by_name['ReplaceLabelsOnNodeRequestProto'] = _REPLACELABELSONNODEREQUESTPROTO
DESCRIPTOR.message_types_by_name['ReplaceLabelsOnNodeResponseProto'] = _REPLACELABELSONNODERESPONSEPROTO
DESCRIPTOR.message_types_by_name['ActiveRMInfoProto'] = _ACTIVERMINFOPROTO

RefreshQueuesRequestProto = _reflection.GeneratedProtocolMessageType('RefreshQueuesRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHQUEUESREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshQueuesRequestProto)
  ))
_sym_db.RegisterMessage(RefreshQueuesRequestProto)

RefreshQueuesResponseProto = _reflection.GeneratedProtocolMessageType('RefreshQueuesResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHQUEUESRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshQueuesResponseProto)
  ))
_sym_db.RegisterMessage(RefreshQueuesResponseProto)

RefreshNodesRequestProto = _reflection.GeneratedProtocolMessageType('RefreshNodesRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHNODESREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshNodesRequestProto)
  ))
_sym_db.RegisterMessage(RefreshNodesRequestProto)

RefreshNodesResponseProto = _reflection.GeneratedProtocolMessageType('RefreshNodesResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHNODESRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshNodesResponseProto)
  ))
_sym_db.RegisterMessage(RefreshNodesResponseProto)

RefreshSuperUserGroupsConfigurationRequestProto = _reflection.GeneratedProtocolMessageType('RefreshSuperUserGroupsConfigurationRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHSUPERUSERGROUPSCONFIGURATIONREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshSuperUserGroupsConfigurationRequestProto)
  ))
_sym_db.RegisterMessage(RefreshSuperUserGroupsConfigurationRequestProto)

RefreshSuperUserGroupsConfigurationResponseProto = _reflection.GeneratedProtocolMessageType('RefreshSuperUserGroupsConfigurationResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHSUPERUSERGROUPSCONFIGURATIONRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshSuperUserGroupsConfigurationResponseProto)
  ))
_sym_db.RegisterMessage(RefreshSuperUserGroupsConfigurationResponseProto)

RefreshUserToGroupsMappingsRequestProto = _reflection.GeneratedProtocolMessageType('RefreshUserToGroupsMappingsRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHUSERTOGROUPSMAPPINGSREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshUserToGroupsMappingsRequestProto)
  ))
_sym_db.RegisterMessage(RefreshUserToGroupsMappingsRequestProto)

RefreshUserToGroupsMappingsResponseProto = _reflection.GeneratedProtocolMessageType('RefreshUserToGroupsMappingsResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHUSERTOGROUPSMAPPINGSRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshUserToGroupsMappingsResponseProto)
  ))
_sym_db.RegisterMessage(RefreshUserToGroupsMappingsResponseProto)

RefreshAdminAclsRequestProto = _reflection.GeneratedProtocolMessageType('RefreshAdminAclsRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHADMINACLSREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshAdminAclsRequestProto)
  ))
_sym_db.RegisterMessage(RefreshAdminAclsRequestProto)

RefreshAdminAclsResponseProto = _reflection.GeneratedProtocolMessageType('RefreshAdminAclsResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHADMINACLSRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshAdminAclsResponseProto)
  ))
_sym_db.RegisterMessage(RefreshAdminAclsResponseProto)

RefreshServiceAclsRequestProto = _reflection.GeneratedProtocolMessageType('RefreshServiceAclsRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHSERVICEACLSREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshServiceAclsRequestProto)
  ))
_sym_db.RegisterMessage(RefreshServiceAclsRequestProto)

RefreshServiceAclsResponseProto = _reflection.GeneratedProtocolMessageType('RefreshServiceAclsResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHSERVICEACLSRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RefreshServiceAclsResponseProto)
  ))
_sym_db.RegisterMessage(RefreshServiceAclsResponseProto)

GetGroupsForUserRequestProto = _reflection.GeneratedProtocolMessageType('GetGroupsForUserRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _GETGROUPSFORUSERREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.GetGroupsForUserRequestProto)
  ))
_sym_db.RegisterMessage(GetGroupsForUserRequestProto)

GetGroupsForUserResponseProto = _reflection.GeneratedProtocolMessageType('GetGroupsForUserResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _GETGROUPSFORUSERRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.GetGroupsForUserResponseProto)
  ))
_sym_db.RegisterMessage(GetGroupsForUserResponseProto)

UpdateNodeResourceRequestProto = _reflection.GeneratedProtocolMessageType('UpdateNodeResourceRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _UPDATENODERESOURCEREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.UpdateNodeResourceRequestProto)
  ))
_sym_db.RegisterMessage(UpdateNodeResourceRequestProto)

UpdateNodeResourceResponseProto = _reflection.GeneratedProtocolMessageType('UpdateNodeResourceResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _UPDATENODERESOURCERESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.UpdateNodeResourceResponseProto)
  ))
_sym_db.RegisterMessage(UpdateNodeResourceResponseProto)

AddToClusterNodeLabelsRequestProto = _reflection.GeneratedProtocolMessageType('AddToClusterNodeLabelsRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _ADDTOCLUSTERNODELABELSREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.AddToClusterNodeLabelsRequestProto)
  ))
_sym_db.RegisterMessage(AddToClusterNodeLabelsRequestProto)

AddToClusterNodeLabelsResponseProto = _reflection.GeneratedProtocolMessageType('AddToClusterNodeLabelsResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _ADDTOCLUSTERNODELABELSRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.AddToClusterNodeLabelsResponseProto)
  ))
_sym_db.RegisterMessage(AddToClusterNodeLabelsResponseProto)

RemoveFromClusterNodeLabelsRequestProto = _reflection.GeneratedProtocolMessageType('RemoveFromClusterNodeLabelsRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEFROMCLUSTERNODELABELSREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RemoveFromClusterNodeLabelsRequestProto)
  ))
_sym_db.RegisterMessage(RemoveFromClusterNodeLabelsRequestProto)

RemoveFromClusterNodeLabelsResponseProto = _reflection.GeneratedProtocolMessageType('RemoveFromClusterNodeLabelsResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEFROMCLUSTERNODELABELSRESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.RemoveFromClusterNodeLabelsResponseProto)
  ))
_sym_db.RegisterMessage(RemoveFromClusterNodeLabelsResponseProto)

ReplaceLabelsOnNodeRequestProto = _reflection.GeneratedProtocolMessageType('ReplaceLabelsOnNodeRequestProto', (_message.Message,), dict(
  DESCRIPTOR = _REPLACELABELSONNODEREQUESTPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.ReplaceLabelsOnNodeRequestProto)
  ))
_sym_db.RegisterMessage(ReplaceLabelsOnNodeRequestProto)

ReplaceLabelsOnNodeResponseProto = _reflection.GeneratedProtocolMessageType('ReplaceLabelsOnNodeResponseProto', (_message.Message,), dict(
  DESCRIPTOR = _REPLACELABELSONNODERESPONSEPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.ReplaceLabelsOnNodeResponseProto)
  ))
_sym_db.RegisterMessage(ReplaceLabelsOnNodeResponseProto)

ActiveRMInfoProto = _reflection.GeneratedProtocolMessageType('ActiveRMInfoProto', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVERMINFOPROTO,
  __module__ = 'server.yarn_server_resourcemanager_service_protos_pb2'
  # @@protoc_insertion_point(class_scope:hadoop.yarn.ActiveRMInfoProto)
  ))
_sym_db.RegisterMessage(ActiveRMInfoProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034org.apache.hadoop.yarn.protoB&YarnServerResourceManagerServiceProtos\210\001\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
