# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: applicationmaster_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yarn_service_protos_pb2 as yarn__service__protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='applicationmaster_protocol.proto',
  package='hadoop.yarn',
  syntax='proto2',
  serialized_pb=_b('\n applicationmaster_protocol.proto\x12\x0bhadoop.yarn\x1a\x19yarn_service_protos.proto2\xfc\x02\n ApplicationMasterProtocolService\x12\x84\x01\n\x19registerApplicationMaster\x12\x32.hadoop.yarn.RegisterApplicationMasterRequestProto\x1a\x33.hadoop.yarn.RegisterApplicationMasterResponseProto\x12~\n\x17\x66inishApplicationMaster\x12\x30.hadoop.yarn.FinishApplicationMasterRequestProto\x1a\x31.hadoop.yarn.FinishApplicationMasterResponseProto\x12Q\n\x08\x61llocate\x12!.hadoop.yarn.AllocateRequestProto\x1a\".hadoop.yarn.AllocateResponseProtoB?\n\x1corg.apache.hadoop.yarn.protoB\x19\x41pplicationMasterProtocol\x88\x01\x01\xa0\x01\x01')
  ,
  dependencies=[yarn__service__protos__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034org.apache.hadoop.yarn.protoB\031ApplicationMasterProtocol\210\001\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
