# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containermanagement_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yarn_service_protos_pb2 as yarn__service__protos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='containermanagement_protocol.proto',
  package='hadoop.yarn',
  syntax='proto2',
  serialized_pb=_b('\n\"containermanagement_protocol.proto\x12\x0bhadoop.yarn\x1a\x19yarn_service_protos.proto2\xe8\x02\n\"ContainerManagementProtocolService\x12\x66\n\x0fstartContainers\x12(.hadoop.yarn.StartContainersRequestProto\x1a).hadoop.yarn.StartContainersResponseProto\x12\x63\n\x0estopContainers\x12\'.hadoop.yarn.StopContainersRequestProto\x1a(.hadoop.yarn.StopContainersResponseProto\x12u\n\x14getContainerStatuses\x12-.hadoop.yarn.GetContainerStatusesRequestProto\x1a..hadoop.yarn.GetContainerStatusesResponseProtoBA\n\x1corg.apache.hadoop.yarn.protoB\x1b\x43ontainerManagementProtocol\x88\x01\x01\xa0\x01\x01')
  ,
  dependencies=[yarn__service__protos__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034org.apache.hadoop.yarn.protoB\033ContainerManagementProtocol\210\001\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
